Traceback (most recent call last):
  File "C:\miniconda3\envs\everything\lib\site-packages\nbclient\client.py", line 730, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "C:\miniconda3\envs\everything\lib\site-packages\nbclient\util.py", line 96, in ensure_async
    result = await obj
  File "C:\miniconda3\envs\everything\lib\site-packages\jupyter_client\channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\miniconda3\envs\everything\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\miniconda3\envs\everything\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\miniconda3\envs\everything\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\miniconda3\envs\everything\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\miniconda3\envs\everything\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\miniconda3\envs\everything\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\miniconda3\envs\everything\lib\site-packages\nbclient\client.py", line 949, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "C:\miniconda3\envs\everything\lib\site-packages\nbclient\client.py", line 754, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "C:\miniconda3\envs\everything\lib\site-packages\nbclient\client.py", line 801, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['# everything stays the same, except training and test data dimension is now reduced', '', "log_params = dict(C=uniform(loc=0.0, scale=20.0), penalty = ['l1', 'l2'])", '', '# fit log regression']
...
["    rand_log_CV = RandomizedSearchCV(rand_log, rand_log_params, n_iter = 50, random_state = 78, n_jobs=6, scoring = 'balanced_accuracy', refit=True).fit(x_train[:, i], y_train)", '    rand_acc.append(metrics.balanced_accuracy_score(y_test, rand_log_CV.predict(x_test[:, i])))', '', '', 'print("average difference in accuracy: {}".format(np.mean(metrics.balanced_accuracy_score(y_test, rank_log_reg_CV.predict(x_test[:, idx])) - np.array(rand_acc))))']
-------------------

